### PR TITLE
Exclude tests from dist

### LINKED ISSUE #35: Remove tests from distributions, or put in-tree, or... ?
`site-packages/tests` is a total dumping ground, and basically useless for anybody.

However, including the tests in the distribution _can_ be useful, but in-tree, such that they can be run with `pytest --pyargs nbclassic`, as well as potentially making test things useful to downstreams, e.g. `from nbclassic.tests import useful_fixture`. Or whatever.

So, I propose one of:
- ignore `tests` with `find_packages(".", exclude=["tests"])`
- keep `tests` where they are, but move `nbclassic` into `src`, and do `find_packages` there
- move `tests` into `nbclassic`

In the interim, I'm working up a PR to the conda-forge feedstock, where a janky `site-packages/tests` cause _particular_ issues for downstream conda tools, e.g. `constructor`, which _really_ (and rightly!) don't like two packages trying to write to the same file... in this case, `tests/conftest.py`.

### PR DESCRIPTION
**Pull request by bollwyvl**
- fixes #35

This is the lowest-change, easiest-to-review approach. 

Can also work up something that:
- adopts the generally-less-error-prone `src/nbclassic/` approach or
- adopts the generally-more-downstream-usable `src/nbclassic/tests` approach

### CODE REVIEW

**Comment by bollwyvl** [comment]
grah, this is the new pip resolver thing, i guess. i dunno, folks. seems shady. I can keep fighting it, but am a bit out of the loop on all the renaming... and why it's bringing in `1.1.0dev` in the first place, and why that constitutes a breaking change.

**Comment by bollwyvl** [comment]
Gah, we're back in the hell that is tornado vs windows vs asyncio vs py38+.

https://github.com/jupyter-server/jupyter_server/pull/339 pays the piper and does the hard cut to `tornado>=6.1`... but for this package, it would require a coordinated release with `notebook` and probably other things that carry the great wounds of that fiasco.

**Comment by Zsailer** [comment]
jupyter_server 1.0.9 has been released and pins tornado>=6.1. Kicked CI here and everything is green! :tada: Thanks, @bollwyvl!

**Comment by bollwyvl** [comment]
Crazy! Glad it worked out.

So do we also need to bump the pin here to ~=1.0.9 prior to the next
release?

**Comment by Zsailer** [comment]
Oops, just released nbclassic 0.2.4 before I saw this.

Yeah, I think it would be a good idea to pin to jupyter_server~=1.0.9.

**Pull request merged**
