### PR TITLE
Depend on notebook_shim package for server-side shim layer

### LINKED ISSUE #87: 0.3.5: pytest is failing
## Description
I'm trying to package your module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

pytest prints error message about change directory to source root.
Issue is that I'm runnig pytest in that location.
Here is pytest output:
```console
+ cd nbclassic-0.3.5
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-nbclassic-0.3.5-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-nbclassic-0.3.5-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/nbclassic-0.3.5, configfile: pyproject.toml, testpaths: nbclassic/tests
plugins: cov-3.0.0, anyio-3.3.4, httpbin-1.0.1, hypothesis-6.36.0, tornasync-0.6.0.post2
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
______________________________________________________________________ ERROR collecting test session _______________________________________________________________________
Defining 'pytest_plugins' in a non-top-level conftest is no longer supported:
It affects the entire test suite instead of just below the conftest as expected.
  /home/tkloczko/rpmbuild/BUILD/nbclassic-0.3.5/nbclassic/conftest.py
Please move it to a top level conftest file at the rootdir:
  /home/tkloczko/rpmbuild/BUILD/nbclassic-0.3.5
For more information, visit:
  https://docs.pytest.org/en/stable/deprecations.html#pytest-plugins-in-non-top-level-conftest-files
========================================================================= short test summary info ==========================================================================
ERROR
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.49s =============================================================================
```
## Expected behavior
Pytest should not fail.
## Context

- Operating System and version: Linux x86/64
- Browser and version: N/A
- JupyterLab version: N/A (`nbclassic` test suite do net require JupyterLab installed)

### PR DESCRIPTION
**Pull request by Zsailer**
Removes all logic that has been moved to [notebook_shim](https://github.com/jupyterlab/notebook_shim).

cc @jtpio 

Also fixes #87

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

The downstream JupyterLab test failure seems relevant: https://github.com/jupyterlab/nbclassic/runs/5309289916?check_suite_focus=true

```
ModuleNotFoundError: No module named 'nbclassic.shim'
```

**Comment by jtpio** [comment]
That's if we want the next release of `nbclassic` to still be backwards compatible with this change.

Maybe we can then keep `nbclassic/shim.py` and re-export the shims from `notebook_shim`.

**Comment by Zsailer** [comment]
How about a shim to a shim? 😆 

I've just shimmed nbclassic's old modules to notebook_shim.

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
