### PR TITLE
Fix deprecation warning when importing jupyter_server.transutils._

### PR DESCRIPTION
**Pull request by martinRenou**
I am seing this warning when starting JupyterLab since a couple of days:
```
lib/python3.9/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
```

I am not sure nbclassic is the culprit here, but I guess it's worth doing it anyway

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

Should the `jupyter_server` dependency also be bumped if this renaming was added to the [`1.5.0` release](
https://github.com/jupyter-server/jupyter_server/releases/tag/1.5.0)?

https://github.com/jupyterlab/nbclassic/blob/0e30d80de5546b50c956ad33ec6e86b6cd554dba/setup.py#L58

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by blink1073** [comment]
Thanks!  I'll cut a release with this tomorrow.

**Comment by martinRenou** [comment]
Thank you!

**Comment by blink1073** [comment]
https://pypi.org/project/nbclassic/0.2.7/

**Pull request merged**
